agent: "DDPG"
env_name: "MuJoCo"
env_id: "Ant-v4"
vectorize: "Dummy_Gym"
policy: "DDPG_Policy"
representation: "Basic_Identical"
runner: "DRL"

representation_hidden_size:  # If you choose Basic_Identical representation, then ignore this value
actor_hidden_size: [400, 300]
critic_hidden_size: [400, 300]
activation: "leaky_relu"
activation_action: 'tanh'

seed: 123
parallels: 4  # number of environments
buffer_size: 200000  # replay buffer size
batch_size: 100
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.005

start_noise: 0.5
end_noise: 0.1
training_frequency: 1
running_steps: 2000000  # 2M
start_training: 10000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

use_grad_bank : True
grad_bank_beta : 0.99
grad_bank_update_freq : 1

test_steps: 10000
eval_interval: 5000
test_episode: 5
log_dir: "./logs/ddpg/"
model_dir: "./models/ddpg/"
