dl_toolbox: "torchAgent"  # The deep learning toolbox. Choices: "torchAgent", "mindspore", "tensorflow"

project_name: "experience_ppo"
# logger: "wandb"  # Choices: "tensorboard", "wandb".

logger: "wandb"
wandb_user_name: "hsingjui-ku"

parallels: 10
seed: 2910
render: True
render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
fps: 50
test_mode: False
test_steps: 2000

device: "cuda:0"

# PyTorch: "cpu", "cuda:0";
# TensorFlow: "cpu"/"CPU", "gpu"/"GPU";
# MindSpore: "CPU", "GPU", "Ascend", "Davinci"

