agent: "TD3"
env_name: "MuJoCo"
env_id: "Ant-v4"
vectorize: "Dummy_Gym"
representation: "Basic_Identical"
policy: "TD3_Policy"
runner: "DRL"

representation_hidden_size:  # If you choose Basic_Identical representation, then ignore this value
actor_hidden_size: [400, 300]
critic_hidden_size: [400, 300]
activation: "leaky_relu"
activation_action: 'tanh'

seed: 321
parallels: 10  # number of environments
buffer_size: 5000000
batch_size: 256
actor_learning_rate: 0.001
actor_update_delay: 2
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.005

start_noise: 0.1
end_noise: 0.1
training_frequency: 1
running_steps: 2000000
start_training: 25000

use_grad_bank : True
grad_bank_beta : 0.99
grad_bank_update_freq : 1

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 5
log_dir: "./logs/td3/"
model_dir: "./models/td3/"
