agent: "DDPG"
env_name: "Box2D"
env_id: "BipedalWalker-v3"
vectorize: "Dummy_Gym"
representation: "Basic_Identical"
policy: "DDPG_Policy"
runner: "DRL"

representation_hidden_size:
actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: "leaky_relu"
activation_action: 'tanh'

seed: 123
parallels: 10  # number of environments
buffer_size: 200000
batch_size: 256
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.005

start_noise: 0.5
end_noise: 0.1
training_frequency: 1
running_steps: 3000000
start_training: 1000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

use_grad_bank : True
grad_bank_beta : 0.99
grad_bank_update_freq : 1

test_steps: 10000
eval_interval: 50000
test_episode: 5
log_dir: "./logs/ddpg/"
model_dir: "./models/ddpg/"